#cloud-config
hostname: mongodb
runcmd:
  - 'sed -i "s/.*\bbindIp\b.*/  bindIp: 10.1.2.50/" /etc/mongod.conf'
  - systemctl restart mongod
  - cd /root/webServer
  - npm run seed
#    - [mkdir, -p, /data/db ]
