#cloud-config
hostname: webserver
runcmd:
  - ifconfig ens4 up 
  - dhclient ens4
  - IPSERVER=`hostname -I | awk '{printf "%s\n", $1}{print $2}' | grep 10.1.1`
  - echo "IPSERVER=$IPSERVER" >> /etc/environment
  - systemctl start mongod
  - pm2 start /root/webServer/rest_server.js --name "consulta-medicos"
  - cd /root/webServer
  - npm start