#cloud-config
hostname: webserver
runcmd:
  - ifconfig ens4 up 
  - dhclient ens4
  - IPSERVER=`hostname -I | awk '{printf "%s\n", $1}{print $2}' | grep 10.1.1`
  - export IPSERVER
  - systemctl start mongod
  - cd /root/webserver
  - npm start