heat_template_version: 2017-02-24
description: Plantilla para definir un server del lb
parameters:

  app_port:
    type: number
    default: 8080
    description: Port used by the servers
  flavor:
    type: string
    description: Flavor used for servers
    constraints:
    - custom_constraint: nova.flavor
  image:
    type: string
    description: Image used for servers
    constraints:
    - custom_constraint: glance.image
  subnet:
    type: string
    description: Subnet on which the load balancer will be located
    constraints:
    - custom_constraint: neutron.subnet
  sec_group:
    type: string
    description: security group for load balancer servers
  pool:
    type: string
    description: pool for lb

resources:
  server1:
    type: OS::Nova::Server
    properties:
      name: server_%index%
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - network: net1
        - network: net2
      security_groups: [{ get_param: sec_group }, open]
      user_data_format: RAW
      user_data:
        { get_file: ../cloud-init/webServer.yaml }

  pool_member1:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_param: pool }
      address: { get_attr: [ server1, first_address ]}
      protocol_port: { get_param: app_port }
      subnet: { get_param: subnet }
